version: 2
updates:
  - package-ecosystem: "npm" 
    versioning-strategy: "auto" =
    directory: "/" 
    schedule:
      interval: "daily" # Check for updates daily
    commit-message:
      prefix: "fix"
    open-pull-requests-limit: 5 # Limit the number of open PRs
